[project]
    name = "toy-rms"
    version = "0.1.0"
    description = "Add your description here"
    readme = "README.md"
    requires-python = ">=3.13"
    dependencies = [
        "dagster>=1.10.21",
        "pandas[parquet]>=2.3.0",
        "polars>=1.31.0",
        "pydantic>=2.11.7",
        "pymongo>=4.13.2",
        "quantlib>=1.38",
        "scipy>=1.15.3",
        "sqlmodel>=0.0.24",
]
