line-length    = 88
target-version = "py310"

[lint]
    exclude = ["examples"]
    ignore  = ["COM", "D203", "D211", "D213", "PLR0912"]
    select  = ["ALL"]

    preview = true

    [lint.per-file-ignores]
        "examples/*" = ["INP001"]
        "examples/test_target.py" = ["F821"]
        "scripts/*.py" = ["INP001", "S101", "T201"]
        "src/debug_dojo/_cli.py" = ["TC003"]
        "src/debug_dojo/_installers.py" = [
            "PLC0415",
            "T100",
        ]
        "tests/*" = ["S101", "T201"]
        "tests/assets/*" = ["F821", "INP001", "T201"]

[format]
    docstring-code-format = true
